# Server Configuration
server.port = 8000

# Database MySQL Configuration (XAMPP)
spring.datasource.url=jdbc:mysql://localhost:3306/db_lost_found?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate otomatis membuat & mengupdate tabel MySQL dari kode Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Thyemeleaf Cache
spring.Thyemeleaf.cache=false

# Google OAuth2 Config
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email